resources:
  - name: mldemo_dbp_repo
    type: GitRepo
    configuration:
      gitProvider: marcus_github                       # <-- replace with your integration
      path: ml-jfrog/jfrog-pipelines-docker-sample    # <-- replace with your repository name
      branches:
        include: master

  - name: mldemo_dbp_image
    type: Image
    configuration:
      registry: ml_artifactory                                # <-- replace with your artifactory integration
      sourceRepository: mldemo-docker-dev-local               # <-- required if registry is Artifactory
      imageName: soleng.jfrog.io/mldemo-docker-dev-local/dbp-demo  # < -- replace with your image path and name
      imageTag: latest
      autoPull: true
      
  - name: mldemo_dbp_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: dbp_build
      buildNumber: 1    

  - name: mldemo_dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: artifactory
      buildName: dbp_build
      buildNumber: 1
      

pipelines:
  - name: marcus_demo_docker
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: soleng.jfrog.io/mldemo-docker-dev-local/dbp-demo  # replace with your image path and name
          dockerImageTag: ${run_number}
          inputResources:
            - name: mldemo_dbp_repo
          integrations:
            - name: ml_artifactory                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker-local
          integrations:
            - name: ml_artifactory                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: mldemo_dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: mldemo_dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: demo-pipelines
          integrations:
            - name: ml_artifactory
          inputResources:
            - name: mldemo_dbp_build_info
          outputResources:
            - name: mldemo_dbp_promoted_build_info

